### ISSUE TITLE
Suppression des exemples dans le narratif

### ISSUE THREAD

**Issue by breverseau** [ansforge/IG-fhir-service-acces-aux-soins#35]
Créer les fichiers exemple en fsh pour tous les cas d'usage et les lier dans les parties narratives. Supprimer les exemples des parties narratives

**Comment by cpanissod** [comment]
A mon sens, il ne faut pas supprimer mais remplacer a minima par un lien vers les exemples, et idéalement pouvoir les embarquer directement dans une div. L'objectif serait d'éviter d'avoir obligatoirement à sortir de la page.

**Comment by nriss** [comment]
Je suis d'accord! Il faut supprimer les exemples tel qu'ils sont écrits en dur actuellement, et les remplacer par un lien ou un embedded

**Comment by breverseau** [comment]
Exemples crées via PR https://github.com/ansforge/IG-fhir-service-acces-aux-soins/pull/50

**Comment by cpanissod** [comment]
@breverseau  c'est mergé via PR #55
